client/urls.py
from django.urls import path
from client.views import register,login, logout_view

app_name = 'client'

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login, name='login'),
    path('logout/', logout_view, name="logout")
]

contact/urls.py
from django.urls import path
from contact.views import (ContactCreateView, ContactListView,
                            ContactUpdateView,ContactDeleteView,
                            RepertoireDetailView)
from django.views.generic.base import RedirectView

app_name = 'contact'

urlpatterns = [
    path('<int:pk>/', ContactCreateView.as_view(),name='create'),
    path('list/<int:pk>/', ContactListView.as_view(),name='list'),
    path('<int:pk>/contacts/', RepertoireDetailView.as_view(), name='detail'),
    path('create/<int:pk>/', ContactCreateView.as_view(), name='create_contact'),
    path('create/<int:pk>/', ContactUpdateView.as_view(),name='create'),
    path('delete/<int:pk>', ContactDeleteView.as_view(),name='delete'), 
]

difusion/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('projet.urls', namespace='repertoire')),
    path('',include('client.urls')),
    path('message/',include('message.urls')),
    path('contact/',include('contact.urls')),
    path('admin/', admin.site.urls),
]

projet/urls.py
from django.urls import path
from projet.views import (RepertoireCreateView, RepertoireListView,
                            RepertoireUpdateView,RepertoireDeleteView)
from django.views.generic.base import RedirectView
from contact.views import ContactCreateView

app_name = 'repertoire'

urlpatterns = [
    path('', RepertoireCreateView.as_view(),name='index'),
    path('list/', RepertoireListView.as_view(),name='list'),
    path('index/<int:pk>/', RepertoireUpdateView.as_view(),name='index'),
    path('delete/<int:pk>', RepertoireDeleteView.as_view(),name='delete'), 
]

projet/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime

class Repertoire(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE, related_name='repertoires')
    nom_repertoire = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now = False,auto_now_add = True)

    def __str__(self):
        return self.nom_repertoire




    

projet/forms.py
from django import forms
from projet.models import Repertoire


#there we are going to create one formulare by instance the class Repository
class RepertoireForm(forms.ModelForm):
    class Meta:
        model = Repertoire
        fields = ['nom_repertoire']
        widgets = {
            'nom_repertoire': forms.TextInput(attrs={'class':'form-control form-is_valid', 'placeholder':'Nom de repertoire'})
        }
        labels = {
            'nom_repertoire':'Nom repertoire',
            
        }

projet/views.py
from django.shortcuts import render
from django.urls import reverse_lazy,reverse
from django.views.generic import CreateView,ListView,DetailView,UpdateView,DeleteView
from projet.models import Repertoire
from projet.forms import RepertoireForm


#now we create a repository
class RepertoireCreateView(CreateView):
    #projet = projet_repertoire.user_id
    form_class = RepertoireForm
    template_name = 'projet/index.html'
    success_url = reverse_lazy('repertoire:list')
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


#we are listing all the repository
class RepertoireListView(ListView):
    model = Repertoire
    template_name = 'projet/list.html'
    context_object_name = 'repertoires'
#we are going to update one repository
class RepertoireUpdateView(UpdateView):
    form_class = RepertoireForm
    template_name = 'projet/index.html'
    success_url = reverse_lazy('repertoire:list')
    model = Repertoire
# end we are going to delete one repository
class RepertoireDeleteView(DeleteView):
    model = Repertoire
    template_name = 'projet/delete_confirm.html'
    context_object_name = 'user'
    success_url = reverse_lazy('repertoire:list')

projet/templates/projet/delete_confirm.html
{% extends 'base.html' %}

{% block title %} Suppression {% endblock %}

{% block content %}
<form  method="POST">
        {% csrf_token %}
        <h3> Voulez vous supprimer {{user.nom}} </h3>
        <a href="{% url 'repertoire:list' %}">Non</a>
        <input type="submit" value=" Oui" class="btn btn-danger">
    </form>
{% endblock %}

projet/templates/projet/index.html
{% extends 'base.html' %}

{% block content %}
    <br><br><br>
    <form method="POST">
        
        <div class="card text-left container card-dark">
            {% if request.user.is_authenticated %}
            <div class="card-header"> <h1 class="text-center text-dark">Creer des repertoires</h1></div>
                <div class="card-body">
                    {% csrf_token %}
                     {{ form.as_p }}
                    <input type="submit" value="Save" class="btn btn-secondary">
                    <a href="{% url 'repertoire:list' %}"><input type="button" value="Liste" class="btn btn-success"></a>
                </div>
            {% endif %}
        </div>
    </form>
{% endblock content %}

projet/templates/projet/list.html
{% extends 'base.html' %}


{% block content %}
<br><br><br>
<div class="container">

    <div class="text text-center"> <h1 class="text-center text-dark">La list de repertoire</h1> </div>
    <br><br>
    <div class="row">
        <table class="table table-bordered">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col"> <h3 class="text-success"> Nom du repertoire</h3></th>
                <th scope="col"> <h3 class="text-success"> Actions</h3></th>
            </tr>
        </thead>
        <tbody>
            {% for repertoire in request.user.repertoires.all %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href="{% url 'contact:detail' pk=repertoire.pk %}">{{ repertoire }}</a></td>
                <td class="text-center"><a href="{% url 'contact:create' pk=repertoire.pk %}" class="btn btn-primary">ajouter contact</a>&thinsp;&thinsp;&thinsp;<a href="{% url 'repertoire:index' pk=repertoire.pk %}" class="btn btn-primary">modifier</a> &thinsp;&thinsp;&thinsp;<a href="{% url 'repertoire:delete' pk=repertoire.pk %}" class="btn btn-danger">supprimer</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>    
    <a href="{% url 'repertoire:index' %}"><input type="submit" value="accueil" class="btn btn-primary"></a>
    &thinsp;&thinsp;

{% endblock %}
</div>
</div>