client/urls.py
from django.urls import path
from client.views import register,login, logout_view

app_name = 'client'

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login, name='login'),
    path('logout/', logout_view, name="logout")
]

difusion/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('projet.urls', namespace='repertoire')),
    path('',include('client.urls')),
    path('message/',include('message.urls')),
    path('contact/',include('contact.urls')),
    path('admin/', admin.site.urls),
]

templates/base/css.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

templates/base/js.html
{% load static %}
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

templates/base/navbar.html
<nav class="navbar navbar-expand-sm bg-primary navbar-dark">
    <div class="container">
        <a class="navbar-brand" href="#">Difusion</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                {% if request.user.is_anonymous %}
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'client:login' %}">Login</a>
                </li>
               {% endif %}
                {% if request.user.is_authenticated %}
                <a href="" class="btn btn-success">{{request.user.username}}</a>
                
                <a href="{% url 'client:logout' %}" class="btn btn-secondary ml-2">Logout</a>
                {% endif%}
                <li class="nav-item">
                    <a class="nav-link active" href="#">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'client:register' %}">register</a>
                </li>
            </ul>

        </div>
    </div>
</nav>