client/urls.py
from django.urls import path
from client.views import register,login, logout_view

app_name = 'client'

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login, name='login'),
    path('logout/', logout_view, name="logout")
]

contact/urls.py
from django.urls import path
from contact.views import (ContactCreateView, ContactListView,
                            ContactUpdateView,ContactDeleteView,
                            RepertoireDetailView)
from django.views.generic.base import RedirectView

app_name = 'contact'

urlpatterns = [
    path('<int:pk>/', ContactCreateView.as_view(),name='create'),
    path('list/<int:pk>/', ContactListView.as_view(),name='list'),
    path('<int:pk>/contacts/', RepertoireDetailView.as_view(), name='detail'),
    path('create/<int:pk>/', ContactCreateView.as_view(), name='create_contact'),
    path('create/<int:pk>/', ContactUpdateView.as_view(),name='create'),
    path('delete/<int:pk>', ContactDeleteView.as_view(),name='delete'), 
]

difusion/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('projet.urls', namespace='repertoire')),
    path('',include('client.urls')),
    path('message/',include('message.urls')),
    path('contact/',include('contact.urls')),
    path('admin/', admin.site.urls),
]

contact/models.py
from django.db import models
from projet.models import Repertoire

# Create your models here.

class Contact(models.Model):
    nom_complet = models.CharField(max_length = 100)
    numero = models.CharField(max_length = 14)
    repertoire=models.ForeignKey(Repertoire,on_delete=models.CASCADE, related_name='contacts')

contact/forms.py
from django import forms
from contact.models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['nom_complet','numero']
        widgets = {
            'nom_complet': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Nom complet'}),
            'numero': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Entrer numero'})
        }
        labels = {
            'nom_complet':'Nom_complete',
            'numero':'numero',
            
        }

contact/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy,reverse
from django.views.generic import CreateView,ListView,DetailView,UpdateView,DeleteView
from contact.models import Contact
from projet.models import Repertoire
from django.contrib.auth.models import User
from contact.forms import ContactForm

# Create your views here.
class ContactCreateView(CreateView):
    #contact = contact_repertoire.user_ids
    form_class = ContactForm
    template_name = 'contact/create.html'
    # success_url = reverse_lazy('repertoire:list', {'pk': sel})
    repertoire_id = None

    def get_success_url(self):
        success_url = reverse_lazy('repertoire:list', kwargs = {'pk': self.repertoire_id})
        print(success_url)
        return success_url

    def form_valid(self, form):
        repertoire = get_object_or_404(Repertoire, pk=self.repertoire_id)
        form.instance.repertoire= repertoire
        print(form)

        return super().form_valid(form)


#we are listing all the contact you have
class ContactListView(ListView):
    model = Contact
    template_name = 'contact/list.html'
    context_object_name = 'users'


#we are going to update one contact 
class ContactUpdateView(UpdateView):
    form_class = ContactForm
    template_name = 'contact/create.html'
    success_url = reverse_lazy('contact:list')
    model = Contact

# end we are going to delete one contact
class ContactDeleteView(DeleteView):
    model = Contact
    template_name = 'contact/delete_confirm.html'
    context_object_name = 'user'
    success_url = reverse_lazy('contact:list')


class RepertoireDetailView(DetailView):
    model = Repertoire
    template_name = 'contact/list.html'
    context_object_name = 'repertoire'

contact/templates/contact/create.html
{% extends 'base.html' %}

{% block content %}
    <br><br><br>
    <form method="POST">
        
        <div class="card text-left container card-dark">
            {% if request.user.is_authenticated %}
            <div class="card-header"> <h1 class="text-center text-dark">Creer des contactes</h1></div>
                <div class="card-body">
                    {% csrf_token %}
                     {{ form.as_p }}
                    <input type="submit" value="Save" class="btn btn-secondary">
                    {% for contact in repertoire.contacts.all %}
                    <a href="{% url 'contact:detail' pk=repertoire.pk %}"><input type="button" value="Liste" class="btn btn-success"></a>
                </div>
                {% endfor %}
            {% endif %}
        </div>
    </form>
{% endblock content %}

contact/templates/contact/delete_confirm.html
{% extends 'base.html' %}

{% block title %} Suppression {% endblock %}

{% block content %}
<form  method="POST">
        {% csrf_token %}
        <h3> Voulez vous supprimer {{user.nom_complet}} </h3>
        <a href="{% url 'contact:list' %}">Non</a>
        <input type="submit" value=" Oui" class="btn btn-danger">
    </form>
{% endblock %}

contact/templates/contact/index.html
{% extends 'base.html' %}

{% block content %}
    <br><br><br>
    <form method="POST">
        
        <div class="card text-left container card-dark">
            {% if request.user.is_authenticated %}
            <div class="card-header"> <h1 class="text-center text-dark">Creer des contactes</h1></div>
                <div class="card-body">
                    {% csrf_token %}
                     {{ form.as_p }}
                    <input type="submit" value="Save" class="btn btn-secondary">
                    <a href="{% url 'contact:list' %}"><input type="submit" value="Liste" class="btn btn-success"></a>
                </div>
            {% endif %}
        </div>
    </form>
{% endblock content %}

contact/templates/contact/list.html
{% extends 'base.html' %}


{% block content %}
<br><br><br>
<div class="container">

    <div class="text text-center"> <h1 class="text-center text-dark">La list des contactes</h1> </div>
    <br><br>
    <div class="row">
        <table class="table table-bordered">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col"> <h3 class="text-success">Nom complet du contact</h3></th>
                <th scope="col"> <h3 class="text-success"> Numero</h3></th>
                <th scope="col"> <h3 class="text-success"> Actions</h3></th>
            </tr>
        </thead>
        <tbody>
            {% for contact in repertoire.contacts.all %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{contact.num_complet}}</td>
                <td>{{contact.numero}}</td>
                <td><a href="{% url 'contact:create' pk=contact.pk %}" class="btn btn-primary">modifier</a>&thinsp;&thinsp;&thinsp; <a href="{% url 'contact:delete' pk=contact.pk %}" class="btn btn-danger">supprimer</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>    
    <a href="{% url 'repertoire:list' %}"><input type="button" value="accueil" class="btn btn-primary"></a> &ensp;
    <a href="{% url 'contact:create_contact' pk=repertoire.pk %}" class="btn btn-secondary">Ajouter un nouveau contact</a>
    &thinsp;&thinsp;

{% endblock %}
</div>
</div>